[package]
name = "tdi_ray_tracer"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_approx_eq = "1.1.0"
crossbeam = "0.8.2"
kanal = "0.1.0-pre8"
png = "0.17.9"
rand = "0.8.5"
strum = "0.25"
strum_macros = "0.25"
tobj = "4.0.0"

[dev-dependencies]
rstest = "0.17.0"
